#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""bash_guard.py — AUTO-GENERATED by generate_hooks.py — DO NOT EDIT

Edit rules.yaml and re-run: python3 .claude/guardrails/generate_hooks.py
catalog_version: 1
Rules: R01, R02, R03"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# Path resolution (pure Python — no bash dependency)
_script_dir = Path(__file__).resolve().parent
_guardrails_dir = str(_script_dir.parent)
os.environ.setdefault('GUARDRAILS_DIR', _guardrails_dir)
hits_file = str(_script_dir.parent / 'hits.jsonl')

data = json.loads(sys.stdin.read())
session_id = data.get('session_id', 'unknown')
command = data.get('tool_input', {}).get('command', '')
cwd = data.get('cwd', os.getcwd())
ts = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

def derive_session_name(session_id, ts, cwd):
    """Derive human-readable name from session's first user message."""
    import pathlib
    date_prefix = ts[:10]
    cache_path = pathlib.Path(os.environ.get('GUARDRAILS_DIR', '')) / 'session_names.json'
    # Check cache
    try:
        if cache_path.exists():
            with open(cache_path, encoding="utf-8") as _cf:
                _cache = json.loads(_cf.read())
            if session_id in _cache:
                return _cache[session_id]
    except (json.JSONDecodeError, OSError, KeyError):
        pass
    # Derive from JSONL
    cwd_hash = cwd.lstrip('/').replace('/', '-')
    jsonl_path = pathlib.Path.home() / f'.claude/projects/{cwd_hash}/{session_id}.jsonl'
    if not jsonl_path.exists():
        return f"{date_prefix}_{session_id[:8]}"
    try:
        with open(jsonl_path, encoding="utf-8") as f:
            for line in f:
                try:
                    rec = json.loads(line.strip())
                    if rec.get('type') == 'human' or (
                        rec.get('message', {}).get('role') == 'user'
                    ):
                        content = rec.get('message', {}).get('content', '')
                        if isinstance(content, list):
                            text = ' '.join(
                                b.get('text', '') for b in content
                                if isinstance(b, dict) and b.get('type') == 'text'
                            )
                        else:
                            text = str(content)
                        if text.strip():
                            slug = re.sub(r'[^a-z0-9]+', '_', text.strip().lower())[:50]
                            slug = slug.strip('_')
                            name = f"{date_prefix}_{slug}"
                            # Write to cache
                            try:
                                _cache_data = {}
                                if cache_path.exists():
                                    with open(cache_path, encoding="utf-8") as _cf2:
                                        _cache_data = json.loads(_cf2.read())
                                _cache_data[session_id] = name
                                with open(cache_path, 'w', encoding="utf-8") as _cf3:
                                    _cf3.write(json.dumps(_cache_data, indent=2))
                            except OSError:
                                pass
                            return name
                except (json.JSONDecodeError, KeyError):
                    continue
    except OSError:
        pass
    return f"{date_prefix}_{session_id[:8]}"


def log_hit(rule_id, enforcement, tool_name, target):
    if not hits_file:
        return
    _sname = derive_session_name(session_id, ts, cwd)
    _aname = os.environ.get('CLAUDE_AGENT_NAME', '')
    rec = json.dumps({
        'ts': ts,
        'rule_id': rule_id,
        'session_id': session_id,
        'session_name': _sname,
        'agent_name': _aname,
        'enforcement': enforcement,
        'tool': tool_name,
        'target': target[:120],
    })
    try:
        with open(hits_file, 'a', encoding="utf-8") as fh:
            fh.write(rec + '\n')
    except OSError:
        pass


# ---------------------------------------------------------------------------
# Rule evaluation — deny > warn > inject > log priority
# _matched_rules: list of (pcode, rule_id, enforcement_str, message)
# pcode: 1=deny, 2=warn, 3=log, 4=inject  (role_guard._code_map)
# ---------------------------------------------------------------------------

_matched_rules = []

# --- R01: pytest-output-block (deny) ---
if not re.search(r'''>\s*(?!/dev/null)\S+\.(?:log|txt|out)\b|\|\s*tee\b|\bpytest\b[^\n]*\btests/\w+\.py\b''', command) and re.search(r'''(?:^|&&|\|\||;|\brun\s+)\s*pytest\b''', command):
    _matched_rules.append((1, 'R01', 'deny', """[GUARDRAIL DENY R01] Full test suite must save output to .test_runs/. Use: pixi run pytest -n 8 -v > .test_runs/$(date +%Y%m%d_%H%M%S).txt 2>&1. Single-file runs (e.g. pytest tests/test_foo.py) are allowed without redirect."""))
# --- R02: pip-install-block (deny) ---
if not re.search(r'''\bpixi\s+run\b''', command) and re.search(r'''(?:^|&&|\|\||;)\s*(?:pip|pip3)\s+install\b''', command):
    _matched_rules.append((1, 'R02', 'deny', """[GUARDRAIL DENY R02] Do not pip install directly — it causes environment drift. Use: pixi add --pypi <package> (PyPI) or pixi add <package> (conda). This keeps pixi.toml as the single source of truth."""))
# --- R03: conda-install-block (deny) ---
if re.search(r'''(?:^|&&|\|\||;)\s*(?:conda|mamba)\s+install\b''', command):
    _matched_rules.append((1, 'R03', 'deny', """[GUARDRAIL DENY R03] Do not conda/mamba install directly — it causes environment drift. Use: pixi add <package>. This keeps pixi.toml as the single source of truth."""))
# --- Bash ack: '# ack:<RULE_ID>' prefix suppresses a warn-level match ---
_ack_match = re.match(r'^#\s*ack:(\S+)', command)
_acked_rule = _ack_match.group(1) if _ack_match else None

# --- hits.jsonl logging (spec §5.3 Item 6 — best-effort, never blocks) ---
_guardrails_dir = os.environ.get('GUARDRAILS_DIR', '.claude/guardrails')
for _pcode, _rid, _enf, _msg in _matched_rules:
    try:
        with open(_guardrails_dir + '/hits.jsonl', 'a', encoding='utf-8') as _hf:
            _hf.write(json.dumps({
                "ts": ts, "rule_id": _rid, "enforcement": _enf,
                "tool": "Bash",
                "agent": os.environ.get("CLAUDE_AGENT_NAME", "unknown"),
                "target": command[:120],
            }) + '\n')
    except Exception:
        pass

# --- Enforcement dispatch: deny > warn > inject > log ---
if _matched_rules:
    _deny_msgs = [_msg for _pcode, _rid, _enf, _msg in _matched_rules if _pcode == 1]
    _warn_msgs = [
        _msg for _pcode, _rid, _enf, _msg in _matched_rules
        if _pcode == 2 and _rid != _acked_rule
    ]
    _inject_rules = [(_rid, _enf, _msg) for _pcode, _rid, _enf, _msg in _matched_rules if _pcode == 4]
    if _deny_msgs:
        print('\n\n'.join(_deny_msgs), file=sys.stderr)
        sys.exit(2)
    elif _warn_msgs:
        print('\n\n'.join(_warn_msgs), file=sys.stderr)
        sys.exit(2)
    elif _inject_rules:
        pass  # inject_transform already applied before this block; proceed
    # log-only (_pcode == 3): recorded to hits.jsonl above; no stderr output
sys.exit(0)
