#!/usr/bin/env python3
"""bash_guard.py — AUTO-GENERATED by generate_hooks.py — DO NOT EDIT

Edit rules.yaml and re-run: python3 .claude/guardrails/generate_hooks.py
catalog_version: fw-test-1
Rules: FW01, FW02, FW05, FW06, FW07, FW08, FW09, FW10, FW11, FW17, FW18, FW20, FW22, FW23, E2E_TEST_RULE"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# Path resolution (pure Python — no bash dependency)
_script_dir = Path(__file__).resolve().parent
_guardrails_dir = str(_script_dir.parent)
os.environ.setdefault('GUARDRAILS_DIR', _guardrails_dir)
hits_file = str(_script_dir.parent / 'hits.jsonl')

data = json.loads(sys.stdin.read())
session_id = data.get('session_id', 'unknown')
command = data.get('tool_input', {}).get('command', '')
cwd = data.get('cwd', os.getcwd())
ts = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

def derive_session_name(session_id, ts, cwd):
    """Derive human-readable name from session's first user message."""
    import pathlib
    date_prefix = ts[:10]
    cache_path = pathlib.Path(os.environ.get('GUARDRAILS_DIR', '')) / 'session_names.json'
    # Check cache
    try:
        if cache_path.exists():
            with open(cache_path) as _cf:
                _cache = json.loads(_cf.read())
            if session_id in _cache:
                return _cache[session_id]
    except (json.JSONDecodeError, OSError, KeyError):
        pass
    # Derive from JSONL
    cwd_hash = cwd.lstrip('/').replace('/', '-')
    jsonl_path = pathlib.Path.home() / f'.claude/projects/{cwd_hash}/{session_id}.jsonl'
    if not jsonl_path.exists():
        return f"{date_prefix}_{session_id[:8]}"
    try:
        with open(jsonl_path) as f:
            for line in f:
                try:
                    rec = json.loads(line.strip())
                    if rec.get('type') == 'human' or (
                        rec.get('message', {}).get('role') == 'user'
                    ):
                        content = rec.get('message', {}).get('content', '')
                        if isinstance(content, list):
                            text = ' '.join(
                                b.get('text', '') for b in content
                                if isinstance(b, dict) and b.get('type') == 'text'
                            )
                        else:
                            text = str(content)
                        if text.strip():
                            slug = re.sub(r'[^a-z0-9]+', '_', text.strip().lower())[:50]
                            slug = slug.strip('_')
                            name = f"{date_prefix}_{slug}"
                            # Write to cache
                            try:
                                _cache_data = {}
                                if cache_path.exists():
                                    with open(cache_path) as _cf2:
                                        _cache_data = json.loads(_cf2.read())
                                _cache_data[session_id] = name
                                with open(cache_path, 'w') as _cf3:
                                    _cf3.write(json.dumps(_cache_data, indent=2))
                            except OSError:
                                pass
                            return name
                except (json.JSONDecodeError, KeyError):
                    continue
    except OSError:
        pass
    return f"{date_prefix}_{session_id[:8]}"


def log_hit(rule_id, enforcement, tool_name, target):
    if not hits_file:
        return
    _sname = derive_session_name(session_id, ts, cwd)
    _aname = os.environ.get('CLAUDE_AGENT_NAME', '')
    rec = json.dumps({
        'ts': ts,
        'rule_id': rule_id,
        'session_id': session_id,
        'session_name': _sname,
        'agent_name': _aname,
        'enforcement': enforcement,
        'tool': tool_name,
        'target': target[:120],
    })
    try:
        with open(hits_file, 'a') as fh:
            fh.write(rec + '\n')
    except OSError:
        pass


def strip_contexts(command, contexts):
    result = command
    if 'python_dash_c' in contexts:
        result = re.sub(
            r"""\bpython3?\s+-c\s+(?:"[^"]*"|'[^']*')""",
            'PYTHON_INLINE_STRIPPED',
            result,
        )
    if 'python_heredoc' in contexts:
        result = re.sub(
            r"""\bpython3?\s+<<\s*['"]?\w+['"]?\n.*?^\w+""",
            'PYTHON_HEREDOC_STRIPPED',
            result,
            flags=re.MULTILINE | re.DOTALL,
        )
    return result


# --- role_guard import for role-gated rules ---
sys.path.insert(0, _guardrails_dir)
import role_guard as _rg
_ACK_TTL_SECONDS = 120  # baked from rules.yaml ack_ttl_seconds

# ---------------------------------------------------------------------------
# Rule evaluation — deny > warn > inject > log priority
# _matched_rules: list of (pcode, rule_id, enforcement_str, message)
# pcode: 1=deny, 2=warn, 3=log, 4=inject  (role_guard._code_map)
# ---------------------------------------------------------------------------

_matched_rules = []

# --- FW01: fw-regex-match-deny (deny) ---
if re.search(r'''\bdangerous_cmd\b''', command):
    _matched_rules.append((1, 'FW01', 'deny', """[FW01] dangerous_cmd is denied."""))
# --- FW02: fw-regex-miss-warn (warn) ---
if not re.search(r'''\bsafe_prefix\b''', command):
    _matched_rules.append((2, 'FW02', 'warn', """[FW02] Command must contain safe_prefix.

To acknowledge and proceed, prefix your command with:
  # ack:FW02 <your command>"""))

# --- FW05: fw-flags-ignorecase (deny) ---
if re.search(r'''\bFLAGTEST\b''', command, re.IGNORECASE):
    _matched_rules.append((1, 'FW05', 'deny', """[FW05] FLAGTEST matched (case-insensitive)."""))
# --- FW06: fw-multi-pattern (deny) ---
if any([re.search(r'''\balpha_bad\b''', command), re.search(r'''\bbeta_bad\b''', command)]):
    _matched_rules.append((1, 'FW06', 'deny', """[FW06] alpha_bad or beta_bad matched."""))
# --- FW07: fw-exclude-if (deny) ---
if not re.search(r'''\bbypass_ok\b''', command) and re.search(r'''\bguarded_action\b''', command):
    _matched_rules.append((1, 'FW07', 'deny', """[FW07] guarded_action is denied (unless bypass_ok present)."""))
# --- FW08: fw-exclude-context (deny) ---
_match_text_FW08 = strip_contexts(command, ['python_dash_c', 'python_heredoc'])
if re.search(r'''\bcontext_word\b''', _match_text_FW08):
    _matched_rules.append((1, 'FW08', 'deny', """[FW08] context_word matched outside stripped contexts."""))
# --- FW09: fw-block-coordinator (deny) ---
if re.search(r'''\bcoord_restricted\b''', command):
    _pcode, _pmsg = _rg.check_role(
        allow=None, block=['Coordinator'],
        enforce='deny', message='[FW09] Coordinator cannot run coord_restricted.')
    if _pcode != 0:
        _matched_rules.append((_pcode, 'FW09', 'deny', _pmsg or """[FW09] Coordinator cannot run coord_restricted."""))

# --- FW10: fw-block-subagent (warn) ---
if re.search(r'''\bsubagent_restricted\b''', command):
    _pcode, _pmsg = _rg.check_role(
        allow=None, block=['Subagent'],
        enforce='warn', message='[FW10] Subagents cannot run subagent_restricted.')
    if _pcode != 0:
        _full_msg = (_pmsg or """[FW10] Subagents cannot run subagent_restricted.""") + """

To acknowledge and proceed, prefix your command with:
  # ack:FW10 <your command>"""
        _matched_rules.append((_pcode, 'FW10', 'warn', _full_msg))

# --- FW11: fw-allow-special (warn) ---
if re.search(r'''\bprivileged_cmd\b''', command):
    _pcode, _pmsg = _rg.check_role(
        allow=['SpecialRole'], block=None,
        enforce='warn', message='[FW11] Only SpecialRole may run privileged_cmd.')
    if _pcode != 0:
        _full_msg = (_pmsg or """[FW11] Only SpecialRole may run privileged_cmd.""") + """

To acknowledge and proceed, prefix your command with:
  # ack:FW11 <your command>"""
        _matched_rules.append((_pcode, 'FW11', 'warn', _full_msg))

# --- FW17: fw-ack-prefix (warn) ---
if re.search(r'''\bwarn_action\b''', command):
    _matched_rules.append((2, 'FW17', 'warn', """[FW17] warn_action requires acknowledgement.

To acknowledge and proceed, prefix your command with:
  # ack:FW17 <your command>"""))
# --- FW18: fw-deny-priority (deny) ---
if re.search(r'''\bwarn_action\b.*\bdeny_also\b''', command, re.DOTALL):
    _matched_rules.append((1, 'FW18', 'deny', """[FW18] deny takes precedence over warn."""))
# --- FW20: fw-log-only (log) ---
if re.search(r'''\blog_this_event\b''', command):
    _pcode, _pmsg = _rg.check_role(
        allow=None, block=['Agent'],
        enforce='log', message='[FW20] Logged event (no block).')
    if _pcode != 0:
        _matched_rules.append((_pcode, 'FW20', 'log', _pmsg or """[FW20] Logged event (no block)."""))

# --- FW22: fw-regex-miss-deny (deny) ---
if not re.search(r'''\bexempt_cmd\b''', command) and not re.search(r'''\brequired_token\b''', command):
    _matched_rules.append((1, 'FW22', 'deny', """[FW22] Command must contain required_token."""))

# --- FW23: fw-block-teamagent (warn) ---
if re.search(r'''\bteam_restricted\b''', command):
    _pcode, _pmsg = _rg.check_role(
        allow=None, block=['TeamAgent'],
        enforce='warn', message='[FW23] All team agents are warned about team_restricted.')
    if _pcode != 0:
        _full_msg = (_pmsg or """[FW23] All team agents are warned about team_restricted.""") + """

To acknowledge and proceed, prefix your command with:
  # ack:FW23 <your command>"""
        _matched_rules.append((_pcode, 'FW23', 'warn', _full_msg))

# --- E2E_TEST_RULE: e2e-test-rule (warn) ---
if re.search(r'''\becho_test_e2e\b''', command):
    _matched_rules.append((2, 'E2E_TEST_RULE', 'warn', """E2E test rule fired

To acknowledge and proceed, prefix your command with:
  # ack:E2E_TEST_RULE <your command>"""))
# --- Bash ack: '# ack:<RULE_ID>' prefix suppresses a warn-level match ---
_ack_match = re.match(r'^#\s*ack:(\S+)', command)
_acked_rule = _ack_match.group(1) if _ack_match else None

# --- hits.jsonl logging (spec §5.3 Item 6 — best-effort, never blocks) ---
_guardrails_dir = os.environ.get('GUARDRAILS_DIR', '.claude/guardrails')
for _pcode, _rid, _enf, _msg in _matched_rules:
    try:
        with open(_guardrails_dir + '/hits.jsonl', 'a') as _hf:
            _hf.write(json.dumps({
                "ts": ts, "rule_id": _rid, "enforcement": _enf,
                "tool": "Bash",
                "agent": os.environ.get("CLAUDE_AGENT_NAME", "unknown"),
                "target": command[:120],
            }) + '\n')
    except Exception:
        pass

# --- Enforcement dispatch: deny > warn > inject > log ---
if _matched_rules:
    _deny_msgs = [_msg for _pcode, _rid, _enf, _msg in _matched_rules if _pcode == 1]
    _warn_msgs = [
        _msg for _pcode, _rid, _enf, _msg in _matched_rules
        if _pcode == 2 and _rid != _acked_rule
    ]
    _inject_rules = [(_rid, _enf, _msg) for _pcode, _rid, _enf, _msg in _matched_rules if _pcode == 4]
    if _deny_msgs:
        print('\n\n'.join(_deny_msgs), file=sys.stderr)
        sys.exit(2)
    elif _warn_msgs:
        print('\n\n'.join(_warn_msgs), file=sys.stderr)
        sys.exit(2)
    elif _inject_rules:
        pass  # inject_transform already applied before this block; proceed
    # log-only (_pcode == 3): recorded to hits.jsonl above; no stderr output
sys.exit(0)
