#!/usr/bin/env python3
"""glob_guard.py — AUTO-GENERATED by generate_hooks.py — DO NOT EDIT

Edit rules.yaml and re-run: python3 .claude/guardrails/generate_hooks.py
catalog_version: fw-test-1
Rules: FW16"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

_script_dir = Path(__file__).resolve().parent
_guardrails_dir = str(_script_dir.parent)
os.environ.setdefault('GUARDRAILS_DIR', _guardrails_dir)
hits_file = str(_script_dir.parent / 'hits.jsonl')

data = json.loads(sys.stdin.read())
session_id = data.get('session_id', 'unknown')
pattern = data.get('tool_input', {}).get('pattern', '')
path = data.get('tool_input', {}).get('path', '')
cwd = data.get('cwd', os.getcwd())
ts = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
tool_name = 'Glob'

def derive_session_name(session_id, ts, cwd):
    """Derive human-readable name from session's first user message."""
    import pathlib
    date_prefix = ts[:10]
    cache_path = pathlib.Path(os.environ.get('GUARDRAILS_DIR', '')) / 'session_names.json'
    # Check cache
    try:
        if cache_path.exists():
            with open(cache_path) as _cf:
                _cache = json.loads(_cf.read())
            if session_id in _cache:
                return _cache[session_id]
    except (json.JSONDecodeError, OSError, KeyError):
        pass
    # Derive from JSONL
    cwd_hash = cwd.lstrip('/').replace('/', '-')
    jsonl_path = pathlib.Path.home() / f'.claude/projects/{cwd_hash}/{session_id}.jsonl'
    if not jsonl_path.exists():
        return f"{date_prefix}_{session_id[:8]}"
    try:
        with open(jsonl_path) as f:
            for line in f:
                try:
                    rec = json.loads(line.strip())
                    if rec.get('type') == 'human' or (
                        rec.get('message', {}).get('role') == 'user'
                    ):
                        content = rec.get('message', {}).get('content', '')
                        if isinstance(content, list):
                            text = ' '.join(
                                b.get('text', '') for b in content
                                if isinstance(b, dict) and b.get('type') == 'text'
                            )
                        else:
                            text = str(content)
                        if text.strip():
                            slug = re.sub(r'[^a-z0-9]+', '_', text.strip().lower())[:50]
                            slug = slug.strip('_')
                            name = f"{date_prefix}_{slug}"
                            # Write to cache
                            try:
                                _cache_data = {}
                                if cache_path.exists():
                                    with open(cache_path) as _cf2:
                                        _cache_data = json.loads(_cf2.read())
                                _cache_data[session_id] = name
                                with open(cache_path, 'w') as _cf3:
                                    _cf3.write(json.dumps(_cache_data, indent=2))
                            except OSError:
                                pass
                            return name
                except (json.JSONDecodeError, KeyError):
                    continue
    except OSError:
        pass
    return f"{date_prefix}_{session_id[:8]}"


def log_hit(rule_id, enforcement, tool_name, target):
    if not hits_file:
        return
    _sname = derive_session_name(session_id, ts, cwd)
    _aname = os.environ.get('CLAUDE_AGENT_NAME', '')
    rec = json.dumps({
        'ts': ts,
        'rule_id': rule_id,
        'session_id': session_id,
        'session_name': _sname,
        'agent_name': _aname,
        'enforcement': enforcement,
        'tool': tool_name,
        'target': target[:120],
    })
    try:
        with open(hits_file, 'a') as fh:
            fh.write(rec + '\n')
    except OSError:
        pass


_matched_rules = []

# --- FW16: fw-glob-root-warn (warn) ---
_root_paths = {'', '.', None}
if cwd:
    _root_paths.add(cwd)
    _root_paths.add(cwd.rstrip('/'))
_has_pattern = '**' in pattern
_is_root = path in _root_paths
if _has_pattern and _is_root:
    _matched_rules.append((2, 'FW16', 'warn', """[FW16] Avoid ** glob from repository root."""))

# --- hits.jsonl logging (best-effort, never blocks) ---
_guardrails_dir = os.environ.get('GUARDRAILS_DIR', '.claude/guardrails')
for _pcode, _rid, _enf, _msg in _matched_rules:
    try:
        with open(_guardrails_dir + '/hits.jsonl', 'a') as _hf:
            _hf.write(json.dumps({
                "ts": ts, "rule_id": _rid, "enforcement": _enf,
                "tool": tool_name,
                "agent": os.environ.get("CLAUDE_AGENT_NAME", "unknown"),
                "target": f"pattern={pattern!r} path={path!r}",
            }) + '\n')
    except Exception:
        pass

# --- Enforcement dispatch: deny > warn > log ---
if _matched_rules:
    _deny_msgs = [_msg for _pcode, _rid, _enf, _msg in _matched_rules if _pcode == 1]
    _warn_msgs = [_msg for _pcode, _rid, _enf, _msg in _matched_rules if _pcode == 2]
    if _deny_msgs:
        print('\n\n'.join(_deny_msgs), file=sys.stderr)
        sys.exit(2)
    elif _warn_msgs:
        print('\n\n'.join(_warn_msgs), file=sys.stderr)
        sys.exit(2)
    # log-only (_pcode == 3): recorded to hits.jsonl above; no stderr output
sys.exit(0)
