#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""write_guard.py — AUTO-GENERATED by generate_hooks.py — DO NOT EDIT

Edit rules.yaml and re-run: python3 .claude/guardrails/generate_hooks.py
catalog_version: 1
Rules: R05"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

_script_dir = Path(__file__).resolve().parent
_guardrails_dir = str(_script_dir.parent)
os.environ.setdefault('GUARDRAILS_DIR', _guardrails_dir)
hits_file = str(_script_dir.parent / 'hits.jsonl')

data = json.loads(sys.stdin.read())
session_id = data.get('session_id', 'unknown')
tool_name = data.get('tool_name', 'Write')
_ti = data.get('tool_input', {})
file_path = _ti.get('file_path') or _ti.get('path') or ''
cwd = data.get('cwd', os.getcwd())
ts = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

def derive_session_name(session_id, ts, cwd):
    """Derive human-readable name from session's first user message."""
    import pathlib
    date_prefix = ts[:10]
    cache_path = pathlib.Path(os.environ.get('GUARDRAILS_DIR', '')) / 'session_names.json'
    # Check cache
    try:
        if cache_path.exists():
            with open(cache_path, encoding="utf-8") as _cf:
                _cache = json.loads(_cf.read())
            if session_id in _cache:
                return _cache[session_id]
    except (json.JSONDecodeError, OSError, KeyError):
        pass
    # Derive from JSONL
    cwd_hash = cwd.lstrip('/').replace('/', '-')
    jsonl_path = pathlib.Path.home() / f'.claude/projects/{cwd_hash}/{session_id}.jsonl'
    if not jsonl_path.exists():
        return f"{date_prefix}_{session_id[:8]}"
    try:
        with open(jsonl_path, encoding="utf-8") as f:
            for line in f:
                try:
                    rec = json.loads(line.strip())
                    if rec.get('type') == 'human' or (
                        rec.get('message', {}).get('role') == 'user'
                    ):
                        content = rec.get('message', {}).get('content', '')
                        if isinstance(content, list):
                            text = ' '.join(
                                b.get('text', '') for b in content
                                if isinstance(b, dict) and b.get('type') == 'text'
                            )
                        else:
                            text = str(content)
                        if text.strip():
                            slug = re.sub(r'[^a-z0-9]+', '_', text.strip().lower())[:50]
                            slug = slug.strip('_')
                            name = f"{date_prefix}_{slug}"
                            # Write to cache
                            try:
                                _cache_data = {}
                                if cache_path.exists():
                                    with open(cache_path, encoding="utf-8") as _cf2:
                                        _cache_data = json.loads(_cf2.read())
                                _cache_data[session_id] = name
                                with open(cache_path, 'w', encoding="utf-8") as _cf3:
                                    _cf3.write(json.dumps(_cache_data, indent=2))
                            except OSError:
                                pass
                            return name
                except (json.JSONDecodeError, KeyError):
                    continue
    except OSError:
        pass
    return f"{date_prefix}_{session_id[:8]}"


def log_hit(rule_id, enforcement, tool_name, target):
    if not hits_file:
        return
    _sname = derive_session_name(session_id, ts, cwd)
    _aname = os.environ.get('CLAUDE_AGENT_NAME', '')
    rec = json.dumps({
        'ts': ts,
        'rule_id': rule_id,
        'session_id': session_id,
        'session_name': _sname,
        'agent_name': _aname,
        'enforcement': enforcement,
        'tool': tool_name,
        'target': target[:120],
    })
    try:
        with open(hits_file, 'a', encoding="utf-8") as fh:
            fh.write(rec + '\n')
    except OSError:
        pass


# Compute relative path for pattern matching
rel_path = file_path
try:
    _abs = Path(file_path)
    if not _abs.is_absolute() and cwd:
        _abs = (Path(cwd) / _abs).resolve()
    if cwd:
        rel_path = str(_abs.relative_to(Path(cwd).resolve()))
except (ValueError, TypeError, OSError):
    pass
rel_path = rel_path.replace(os.sep, '/')

# --- role_guard import for role-gated rules and ack token checks ---
sys.path.insert(0, _guardrails_dir)
import role_guard as _rg
_ACK_TTL_SECONDS = 60  # baked from rules.yaml ack_ttl_seconds

# ---------------------------------------------------------------------------
# Rule evaluation — deny > warn > inject > log priority
# _matched_rules: list of (pcode, rule_id, enforcement_str, message)
# pcode: 1=deny, 2=warn, 3=log, 4=inject  (role_guard._code_map)
# ---------------------------------------------------------------------------

_matched_rules = []

# --- R05: subagent-guardrail-config-block (deny) ---
_field_R05 = data.get('tool_input', {}).get('file_path', '')
if re.search(r'''\.claude/guardrails/''', _field_R05):
    _pcode, _pmsg = _rg.check_role(
        allow=None, block=['Subagent'],
        enforce='deny', message='[GUARDRAIL DENY R05] Guardrail config is managed by Coordinator only.')
    if _pcode == 2:  # warn — ack token flow available
        if _rg.check_write_ack('R05', file_path, _ACK_TTL_SECONDS):
            pass  # ack token valid — allow
        else:
            _ack_cmd = f'python3 .claude/guardrails/role_guard.py ack R05 {file_path}'
            _matched_rules.append((
                2, 'R05', 'deny',
                (_pmsg or """[GUARDRAIL DENY R05] Guardrail config is managed by Coordinator only.""")
                + f'\n\nTo acknowledge and proceed:\n  {_ack_cmd}'
                + f'\nThen retry within {_ACK_TTL_SECONDS} seconds.'
                + '\n(If the retry still rejects, the ack token may have expired — re-run the ack command.)'
            ))
    elif _pcode == 1:  # deny — no ack option
        _matched_rules.append((1, 'R05', 'deny', _pmsg or """[GUARDRAIL DENY R05] Guardrail config is managed by Coordinator only."""))
    elif _pcode not in (0, 2, 1):
        _matched_rules.append((_pcode, 'R05', 'deny', _pmsg or """[GUARDRAIL DENY R05] Guardrail config is managed by Coordinator only."""))

# --- hits.jsonl logging (spec §5.3 Item 6 — best-effort, never blocks) ---
_guardrails_dir = os.environ.get('GUARDRAILS_DIR', '.claude/guardrails')
for _pcode, _rid, _enf, _msg in _matched_rules:
    try:
        with open(_guardrails_dir + '/hits.jsonl', 'a', encoding='utf-8') as _hf:
            _hf.write(json.dumps({
                "ts": ts, "rule_id": _rid, "enforcement": _enf,
                "tool": tool_name,
                "agent": os.environ.get("CLAUDE_AGENT_NAME", "unknown"),
                "target": file_path,
            }) + '\n')
    except Exception:
        pass

# --- Enforcement dispatch: deny > warn > inject > log ---
if _matched_rules:
    _deny_msgs = [_msg for _pcode, _rid, _enf, _msg in _matched_rules if _pcode == 1]
    _warn_msgs = [_msg for _pcode, _rid, _enf, _msg in _matched_rules if _pcode == 2]
    _inject_rules = [(_rid, _enf, _msg) for _pcode, _rid, _enf, _msg in _matched_rules if _pcode == 4]
    if _deny_msgs:
        print('\n\n'.join(_deny_msgs), file=sys.stderr)
        sys.exit(2)
    elif _warn_msgs:
        print('\n\n'.join(_warn_msgs), file=sys.stderr)
        sys.exit(2)
    elif _inject_rules:
        pass  # inject_transform already applied; proceed
    # log-only (_pcode == 3): recorded to hits.jsonl above; no stderr output
sys.exit(0)
